{% set name = "pyprep" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/source/{{ name[0] }}/{{ name }}/pyprep-{{ version }}.tar.gz
  sha256: c9f2c7cd524a4732b3d953e507478813f732bffe780cccd4b94841f64ecdddd6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.20.2
    - scipy >=1.6.3
    - mne-base >=1.3.0
    - psutil >=5.4.3

test:
  imports:
    - pyprep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sappelhoff/pyprep
  summary: A Python implementation of the preprocessing pipeline (PREP) for EEG data.
  dev_url: https://github.com/sappelhoff/pyprep
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
    - a-hurst
