{% set name = "pyprep" %}
{% set version = "0.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyprep-{{ version }}.tar.gz
  sha256: 4e7713f214bdcbb23f1c1f1eb20602e13731961bd33d1b5fc78a1c38d02fbac0

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - numpy >=1.20.2
    - scipy >=1.6.3
    - mne-base >=1.3.0
    - psutil >=5.4.3

test:
  imports:
    - pyprep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sappelhoff/pyprep
  summary: A Python implementation of the preprocessing pipeline (PREP) for EEG data.
  dev_url: https://github.com/sappelhoff/pyprep
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
    - a-hurst
