{% set name = "pyprep" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pyprep-{{ version }}.tar.gz
  sha256: 6df407b127acfef26ea1d3b768d6cebbcdd469b2bbb7ca66dec5c6ac517b89ed

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - numpy >=1.20.2
    - scipy >=1.6.3
    - mne-base >=1.3.0
    - psutil >=5.4.3

test:
  imports:
    - pyprep
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/sappelhoff/pyprep
  summary: A Python implementation of the preprocessing pipeline (PREP) for EEG data.
  dev_url: https://github.com/sappelhoff/pyprep
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
    - a-hurst
