{% set name = "pyprep" %}
{% set version = "0.4.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyprep-{{ version }}.tar.gz
  sha256: 965a4aadcc65e66ea8bd6b43305828b0f30f47d34aca66075dd9d48a407e41ae

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7
    - numpy >=1.14.1
    - scipy >=1.0.0
    - mne >=0.20.0
    - psutil >=5.4.3

test:
  imports:
    - pyprep
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sappelhoff/pyprep
  summary: A Python implementation of the preprocessing pipeline (PREP) for EEG data.
  dev_url: https://github.com/sappelhoff/pyprep
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - sappelhoff
    - a-hurst
